apiVersion: v1
kind: Service
metadata:
  name: crud-app-backend-service
  namespace: crud-app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
