apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-crud-app
  namespace: crud-app
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: final_assignment-backend
          imagePullPolicy: Never
          env:
            - name: db_address
              value: crud-app-postgres-service
            - name: db_username
              value: postgres
            - name: db_name
              value: postgres
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: crud-app-secret
                  key: password
          ports:
            - containerPort: 8000
