apiVersion: v1
kind: Service
metadata:
  name: crud-app-postgres-service
  namespace: crud-app
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432